# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install --upgrade setuptools
            make install-dev
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m coverage run --rcfile=.coveragerc
            python3 -m py.test -c pytest.ini tests/unit
            python3 -m coverage run --rcfile=.coveragerc
            python3 -m py.test -c pytest.ini tests/integration
